/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/utils/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations["health_check_utils_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Document */
    post: operations["create_document_documents_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{document_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Document */
    get: operations["get_document_documents__document_id__get"];
    /** Save Document */
    put: operations["save_document_documents__document_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{document_id}/chars": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Insert Char */
    post: operations["insert_char_documents__document_id__chars_post"];
    /** Delete Char */
    delete: operations["delete_char_documents__document_id__chars_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user_id}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Documents */
    get: operations["get_user_documents_users__user_id__documents_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CharIdSchema */
    CharIdSchema: {
      /** Local Counter */
      local_counter: number;
      /** User Id */
      user_id: number;
    };
    /** CharSchema */
    CharSchema: {
      char_id: components["schemas"]["CharIdSchema"];
      /** Value */
      value: string;
      parent_id?: components["schemas"]["CharIdSchema"] | null;
      /** Deleted */
      deleted: boolean;
    };
    /** CreateDocumentPayload */
    CreateDocumentPayload: {
      /** Owner Id */
      owner_id: number;
      /** Title */
      title: string;
      /** Description */
      description: string;
    };
    /** CreateDocumentResponse */
    CreateDocumentResponse: {
      /** Document Id */
      document_id: number;
    };
    /** DeleteCharPayload */
    DeleteCharPayload: {
      /** Owner Id */
      owner_id: number;
      char_id: components["schemas"]["CharIdSchema"];
    };
    /** DocumentResponse */
    DocumentResponse: {
      /** Id */
      id: number;
      /** Owner Id */
      owner_id: number;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Allowed To Modify */
      allowed_to_modify: number[];
      /** Version */
      version: number;
      /** Content */
      content: components["schemas"]["CharSchema"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InsertCharPayload */
    InsertCharPayload: {
      /** Owner Id */
      owner_id: number;
      /** Value */
      value: string;
      /** Local Counter */
      local_counter: number;
      parent_id?: components["schemas"]["CharIdSchema"] | null;
    };
    /** SaveDocumentPayload */
    SaveDocumentPayload: {
      /** Title */
      title: string;
      /** Description */
      description: string;
    };
    /** SaveDocumentResponse */
    SaveDocumentResponse: {
      /** Saved Index */
      saved_index: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_check_utils_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  create_document_documents_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDocumentPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateDocumentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_document_documents__document_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  save_document_documents__document_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveDocumentPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SaveDocumentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  insert_char_documents__document_id__chars_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InsertCharPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CharSchema"] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_char_documents__document_id__chars_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteCharPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CharSchema"] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_documents_users__user_id__documents_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
